### ISSUE TITLE
Makefile.PL requires latest version(Perl 5.14.2)

### ISSUE THREAD

**Issue by syohex** [ysasaki/p5-sub-apply#1]
Makefile.PL contains 'use 5.014002' so that Makefile.PL cannot be executed on platform
using older perl(< 5.14.2).  But lib/Sub/Apply.pm requires version 5.008008 higher.

I think you should use MIN_PERL_VERSION which is the WriteMakefile parameter
to require minimal Perl version.

Thanks.

**Comment by ysasaki** [comment]
I fixed it. thanks!
